services:

  frontend:
    image: node:20
    volumes:
      - .:/var/www/html/:rw
    working_dir: /var/www/html
    user: ${UID:-1000}:${GID:-1000}
    ports:
      - 3000:3000
    command:
      - "yarn"
      - "dev"


networks:
  default:
    name: refugeework
